{% set name = "researchpy" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/researchpy-{{ version }}.tar.gz
  sha256: e2afb45097dce2cc1da391ac9c7803015287632255fa56bf413a23984aa70399

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - scipy
    - numpy
    - pandas
    - statsmodels
    - patsy

test:
  imports:
    - researchpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/researchpy/researchpy
  summary: Researchpy produces Pandas DataFrames that contain relevant statistical testing information that is commonly required for academic research.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
