{% set name = "researchpy" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2afb45097dce2cc1da391ac9c7803015287632255fa56bf413a23984aa70399

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools >=61.0
    - pip
    - wheel
  run:
    - python
    - scipy
    - numpy
    - pandas
    - statsmodels
    - patsy

test:
  imports:
    - researchpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/researchpy/researchpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Researchpy produces Pandas DataFrames that contain relevant statistical testing information that is commonly required for academic research.
  description: |
    researchpy produces Pandas DataFrames that contain relevant statistical testing
    information that is commonly required for academic research. The information is
    returned as Pandas DataFrames to make for quick and easy exporting of results to
    any format/method that works with the traditional Pandas DataFrame.
  doc_url: https://github.com/researchpy/documentation
  dev_url: https://github.com/researchpy/researchpy

extra:
  recipe-maintainers:
    - rxm7706
